[package]
name = "rundtisch-demo-worker"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rundtisch = { path = "../../crates/rundtisch", default-features = false }
rundtisch-demo = { path = "../api", default-features = false}
tower-service = "0.3"
worker-macros = { version = "0.8", features = ["http"] }
axum = "0.8.9"
worker = "0.8.5"

