[package]
name = "rundtisch-demo-worker"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rundtisch = { path = "../../crates/rundtisch", default-features = false }
rundtisch-demo = { path = "../api", default-features = false, features = ["cloudflare"] }
tower-service.workspace = true
axum.workspace = true
worker-macros = { workspace = true, features = ["http"] }
worker = { workspace = true, features = ["http"] }
