[workspace]
resolver = "2"
members = [".", "worker"]
default-members = ["."]

[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[features]
default = []
native = ["dep:tokio", "axum/tokio"]
cloudflare = ["dep:worker"]

# Shared — safe for both runtimes
[dependencies]
axum = { version = "0.8", default-features = false, features = ["json", "http1"] }
#serde = { version = "1.0", features = ["derive"] }
#thiserror = "2.0.18"
serde_json = "1.0"
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "net", "signal"], optional = true }
worker = { version = "0.8", features = ["http", "axum"], optional = true }

[[bin]]
name = "native_server"
path = "src/bin/native_server.rs"
required-features = ["native"]
