[package]
name = "rundtisch"
version.workspace = true
edition.workspace = true
description = "Micro web framework with hexagonal architecture"
repository = "https://github.com/danac/rundtisch"
readme = "README.md"
publish = false

[features]
default = []
d1 = ["worker/d1", "time/wasm-bindgen"]
sqlite = ["sqlx/sqlite", "sqlx/runtime-tokio"]

[dependencies]
sea-query.workspace = true
serde = { workspace = true, features = ["derive", "alloc"] }
email_address = { workspace = true, features = ["serde"] }
sqlx = { workspace = true, optional = true }
worker = { workspace = true, optional = true }
time = { workspace = true, features = ["std", "formatting", "parsing", "serde", "serde-well-known"] }
axum = { workspace = true, features = ["json"] }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"]}
tower = { version = "0.5", default-features = false, features = ["util"] }
