[package]
name = "rundtisch"
version.workspace = true
edition.workspace = true
description = "Micro web framework with hexagonal architecture"
repository = "https://github.com/danac/rundtisch"
readme = "README.md"
publish = false

[features]
default = []
d1 = ["worker/d1"]
sqlite = ["sqlx/sqlite"]

[dependencies]
email_address = "0.2.9"
sea-query = "1.0.1"
time = { version = "0.3.53", default-features = false, features = ["formatting", "parsing"] }
sqlx = { version = "0.9.0", optional = true }
worker = { version = "0.8", optional = true }

[dev-dependencies]
tokio = { version= "1.52.3", features=["macros", "rt"] }
