[package]
name = "rundtisch-demo"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
rundtisch = { path = "../../crates/rundtisch" }
serde_json.workspace = true
axum = { workspace = true, features = ["json", "http1", "tokio"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "signal"] }
sea-orm = { workspace = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "sqlx-mysql",
    "sqlx-postgres",
] }
sea-orm-migration = { workspace = true, features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "sqlx-mysql",
    "sqlx-postgres",
] }
async-trait.workspace = true

[[bin]]
name = "native"
path = "src/bin/native.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"
