[package]
name = "rundtisch-demo"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
native = ["rundtisch/native", "dep:tokio", "axum/tokio"]
cloudflare = ["rundtisch/cloudflare"]

[dependencies]
axum.workspace = true
rundtisch = { path = "../../crates/rundtisch", default-features = false }
serde_json.workspace = true
tokio = { workspace = true, optional = true }

[[bin]]
name = "native"
path = "src/bin/native.rs"
required-features = ["native"]

[[bin]]
name = "generate_auth_migrations"
path = "src/bin/generate_auth_migrations.rs"
